package com.pxy.visaz.ui.applyvisa

data class VisaSubmitApplicationModel(
    var travelDate: String,
    var nationality: String,
    var nationalId: String,
    var fullName: String,
    var contactNumber: String,
    var email: String,
    var gender: String,
    var maritalStatus: String,
    var husbandName: String,
    var motherName: String,
    var fatherName: String,
    var currentResidentialAddress: String,
    var nameOfBusiness: String,
    var addressOfBusiness: String,
    var employerDesignation: String,
    var panNumber: String,
    var occupation: String,
    var religion: String,
    var educationQualification: String,
    var mainLanguageSpoken: String,
    var dob: String,
    var placeOfBirthCountry: String,
    var passportNumber: String,
    var purposeOfVisit: String,
    var countryContactName: String,
    var relationshipWithHost: String,
    var addressOrHotelConfirmation: String,
    var voucherArea: String,
    var profileImage: String,
    var passport: String,
    var previousPassport: String,
    var longTermFd: String,
    var incomeTaxReturns: String,
    var letterOfInvitation: String
)

